#!/bin/bash
set -euo pipefail
cd /usr/ictcore/db

# Generate db/core_seed.sql by extracting top-level (column-0) INSERT INTO
# statements from legacy database.sql. This gives us all reference and seed
# data (permission, role, role_permission, country, currency, language,
# timezone, region, codec, configuration, carriertype, auto_number, etc.)
# while skipping schema objects (CREATE TABLE/TRIGGER/PROCEDURE bodies) —
# their `INSERT INTO ...` lines have leading whitespace and are not matched.
#
# The single mid-file INSERT INTO account is inside a CREATE TRIGGER body —
# anchored regex skips it correctly.

OUT=core_seed.sql

{
  cat <<'HDR'
-- core_seed.sql — reference + permission/role seed data for ICTCore.
--
-- WHY THIS FILE EXISTS
-- -----------------------------------------------------------------------------
-- db/mariadb-schema.sql is a mysqldump --no-data style dump (structure only).
-- The installer prefers mariadb-schema.sql over the legacy database.sql when
-- both are present, so reference data (permission, role, country, currency,
-- language, timezone, region, codec, configuration, etc.) never gets seeded
-- on a fresh CE/EE install.
--
-- Without this file, a fresh install has:
--   * permission table with only the password_policy row (from
--     password_policy.sql) — missing the 118 core permissions including
--     super_admin, api, *_read/*_create/*_list, etc.
--   * empty role_permission table — admin user has no super_admin grant
--   * AuthenticateApi::create() takes the !super_admin branch on admin login
--     and trips password-expiry => HTTP 426 "User password has expired"
--
-- Loaded by ictcore-install.sh and ictcore-ce-install.sh from SCHEMA_FILES
-- immediately after the base schema. Re-runs on a populated DB emit
-- duplicate-key warnings the installer already swallows.
--
-- Generated by tools/build-core-seed.sh from database.sql (top-level INSERTs).
-- Generated body first, then hand-maintained additions at the end of the file
-- (QA permission backfills, and a node row with the sample credentials
-- scrubbed). Re-running this script rewrites the whole file and would drop
-- those, so diff before you replace anything.
-- =============================================================================

HDR
  # Print the WHOLE statement, not just its first line. Most top-level
  # INSERTs in database.sql are one-liners, but the configuration_data
  # INSERT...SELECT spans four lines. Printing line one alone left a bare
  # "INSERT INTO configuration_data" in the output, mysql read the next
  # line as part of it, and the syntax error stopped the whole file dead
  # at that point — taking 726 seed rows with it on every fresh install.
  # A statement ends at a line whose last code character is a semicolon,
  # allowing for a trailing -- comment (several gateway rows have one).
  awk '
    /^INSERT INTO/ { inside = 1 }
    inside         { print }
    inside && /;[[:space:]]*(--.*)?$/ { inside = 0 }
  ' database.sql
} > "$OUT"

chown ictcore:ictcore "$OUT"

echo "----- $OUT stats -----"
wc -l "$OUT"
echo "Total INSERTs: $(grep -c '^INSERT INTO' "$OUT")"
echo "permission INSERTs: $(grep -c '^INSERT INTO permission' "$OUT")"
echo "role INSERTs:       $(grep -c '^INSERT INTO role ' "$OUT")"
echo "role_permission:    $(grep -c '^INSERT INTO role_permission' "$OUT")"
echo "country INSERTs:    $(grep -c '^INSERT INTO country' "$OUT")"
echo "Tables seeded:"
grep '^INSERT INTO' "$OUT" | awk '{print $3}' | sort -u | tr '\n' ' '; echo
